### ISSUE TITLE
Consider using more loose version range for requests in requirements.txt

### ISSUE THREAD

**Issue by whummer** [localstack/verdin#1]
Consider using more loose version range for `requests` in requirements.txt:
https://github.com/localstack/verdin/blob/519f3e02963341db8e2966bbb31916b78b65034f/setup.cfg#L30

This is currently causing issues in other places - to be discussed... (potentially the version ranges should be loosened up in other places as well..)

**Comment by thrau** [comment]
Resolved with 0.1.0
